import os

COSMOS_CONNECTION_STRING = os.environ.get("COSMOS_CONNECTION_STRING")
COSMOS_DB_NAME = os.environ.get("COSMOS_DB_NAME")
COSMOS_DB_CONTENT_COLLECTION_NAME = os.environ.get("COSMOS_DB_CONTENT_COLLECTION_NAME")
COSMOS_DB_METADATA_COLLECTION_NAME = os.environ.get("COSMOS_DB_METADATA_COLLECTION_NAME")

if not COSMOS_CONNECTION_STRING:
    raise ValueError("COSMOS_CONNECTION_STRING is not set")
if not COSMOS_DB_NAME:
    raise ValueError("COSMOS_DB_NAME is not set")
if not COSMOS_DB_CONTENT_COLLECTION_NAME:
    raise ValueError("COSMOS_DB_CONTENT_COLLECTION_NAME is not set")
if not COSMOS_DB_METADATA_COLLECTION_NAME:
    raise ValueError("COSMOS_DB_METADATA_COLLECTION_NAME is not set")